name: Playwright Tests

on:
  pull_request:
    branches: [main]

jobs:

  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Run setup (install, build, clean)
        run: npm run setup
  
  test:
    needs: setup
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password123
          POSTGRES_DB: testdb
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          
    strategy:
      matrix:
        tag: ["@ui", "@api", "@db"]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Load .env File
        run: |
          echo "BASE_URL=${{ secrets.BASE_URL }}" >> $GITHUB_ENV
          echo "UI_USERNAME=${{ secrets.UI_USERNAME }}" >> $GITHUB_ENV
          echo "UI_PASSWORD=${{ secrets.UI_PASSWORD }}" >> $GITHUB_ENV
          echo "API_BASE_URL=${{ secrets.API_BASE_URL }}" >> $GITHUB_ENV
          echo "API_USERNAME=${{ secrets.API_USERNAME }}" >> $GITHUB_ENV
          echo "API_PASSWORD=${{ secrets.API_PASSWORD }}" >> $GITHUB_ENV
          echo "DB_HOST=localhost" >> $GITHUB_ENV
          echo "DB_PORT=5432" >> $GITHUB_ENV
          echo "DB_USER=postgres" >> $GITHUB_ENV
          echo "DB_PASSWORD=password123" >> $GITHUB_ENV
          echo "DB_NAME=testdb" >> $GITHUB_ENV

      - name: Run Playwright tests
        run: npx playwright test --grep ${{ matrix.tag }}

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: ${{ matrix.tag }}-report
          path: playwright-report/
          retention-days: 30
